### ISSUE TITLE
Not just for server side: this can be very useful for unit testing

### ISSUE THREAD

**Issue by atesgoral** [jamestalmage/ng-utils#1]
I found this library while looking around to find a drop-in replacement for Angular's utilities. I hate the fact that Angular requires a browser environment (headless or not). It's impossible to unit test a module that makes use of Angular's utilities without providing a browser environment to make Angular happy. Will give it a shot and report back. Just wanted to comment on this potential usage avenue. I might end up cutting a PR if I find any interop issues....

**Comment by jamestalmage** [comment]
It will probably only work for testing if your module does not use any other angular services, i.e. you are not injecting `$q`, `$http`, `$timeout`, `$scope`, `$exceptionHandler`, etc.  Those are services who have useful mock implementations in the `ngMock` lib.

I had headless testing as a goal of the library initially, but I have found I quickly reach roadblocks where I still need the browser. If the code in question is only ever going to run in the browser, just stick to testing in karma. You really should only use this for code you intend to run on both the server and client (validation code, etc).

**Comment by atesgoral** [comment]
Yup :) I mock Angular services. My test targets are generally services or classes that don't have tight coupling with Angular itself, and are strictly things that are deemed worth unit testing. The Angular utils are the only remaining roadblock. I use The Intern for unit testing because I don't like the idea of booting up a browser when it comes to unit testing. The Intern runs blazingly fast with a simple `npm install` (no PhantomJS etc. required). I have no intentions of switching to Karma :)

**Comment by atesgoral** [comment]
Please see #2
